# Generated by Django 4.2.7 on 2025-12-31 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("project_type", models.CharField(blank=True, max_length=100)),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("detailed_description", models.TextField(blank=True)),
                ("featured_image", models.ImageField(upload_to="projects/")),
                ("project_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                (
                    "budget",
                    models.CharField(
                        blank=True, help_text="e.g., $50,000 - $100,000", max_length=100
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, help_text="e.g., 3 months", max_length=100
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="portfolio.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-project_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class, e.g., 'fas fa-paint-brush'",
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="List features separated by commas"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Ctrin Interiors", max_length=200),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=200)),
                ("footer_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("designer", "Interior Designer"),
                            ("architect", "Architect"),
                            ("coordinator", "Project Coordinator"),
                            ("manager", "Project Manager"),
                            ("founder", "Founder"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="team/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("specialization", models.CharField(blank=True, max_length=200)),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON format: {'twitter': 'url', 'linkedin': 'url'}",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=200)),
                ("client_position", models.CharField(blank=True, max_length=200)),
                ("client_company", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                (
                    "client_image",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField()),
                ("featured_image", models.ImageField(upload_to="blog/")),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Tags separated by commas", max_length=200
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
