# Generated by Django 4.2.7 on 2025-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="Kutta", max_length=200),
        ),
    ]
