# Generated by Django 4.2.7 on 2025-12-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_sitesettings_site_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="logo",
        ),
    ]
