# Generated by Django 4.2.7 on 2025-12-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_sitesettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(blank=True, upload_to="site/"),
        ),
    ]
